### ISSUE TITLE
知道怎么改成多进程版本吗?

### ISSUE THREAD

**Issue by 625781186** [zibuyu1995/ApplicationInImageProcessing#20]
我看了下感觉 生成index和 search 都可以用多进程的版本

**Comment by zibuyu1995** [comment]
可以改为多进程但是sanic和flask都不支持concurrent  ProcessPoolExecutor, 生成索引已经是多进程的，如果搜索如果要改为多进程那么就不支持web搜索。

**Comment by zibuyu1995** [comment]
> 我看了下感觉 生成index和 search 都可以用多进程的版本

可以改为多进程但是sanic和flask都不支持concurrent ProcessPoolExecutor, 生成索引已经是多进程的，如果搜索如果要改为多进程那么就不支持web搜索。

**Comment by 625781186** [comment]
> > 我看了下感觉 生成index和 search 都可以用多进程的版本
> 
> 可以改为多进程但是sanic和flask都不支持concurrent ProcessPoolExecutor, 生成索引已经是多进程的，如果搜索如果要改为多进程那么就不支持web搜索。

ApplicationInImageProcessing/imageSearchEngineWithPython/app/index.py 是生成索引吧, 还是不是多进程呀.

**Comment by zibuyu1995** [comment]
这个还没重构呢，你可以看一下ApplicationInImageProcessing
<https://github.com/zibuyu1995/ApplicationInImageProcessing>/ORB-imageSearch
<https://github.com/zibuyu1995/ApplicationInImageProcessing/tree/master/ORB-imageSearch>
/generate_index.py 就是多进程版

625781186 <notifications@github.com> 于2018年11月13日周二 下午9:57写道：
